### PR TITLE
Using find with exec instead of recusing for setting files mtime

### PR DESCRIPTION
**Pull request by chelarua**
Related to #33.
As suggested to use find with -exec.

### CODE REVIEW

**Comment by ringods** [comment]
@raphaelcohn could you publish a new packaged version?

**Comment by raphaelcohn** [comment]
Ringo

Can do Monday - does that work for you?

Raphael Cohn
Chief Architect, StormMQ
Co-Chair, OASIS MQTT Standard for the Internet of Things
Advisor, UK Government Technical Standards Board
https://uk.linkedin.com/in/raphcohn
+44 7590 675 756

UK Office:
Hamblethorpe Farm, Crag Lane, Bradley BD20 9DB, North Yorkshire, United
Kingdom
+44 845 3712 567

Registered office:
16 Anchor Street, Chelmsford, Essex, CM2 0JY, United Kingdom
StormMQ IT Limited is Registered in England and Wales under Company Number
07175657

**Comment by ringods** [comment]
Great!!

Have a nice weekend!

Ringo

On Friday, 13 November 2015, Raphael Cohn <notifications@github.com> wrote:

> Ringo
>
> Can do Monday - does that work for you?
>
> Raphael Cohn
> Chief Architect, StormMQ
> Co-Chair, OASIS MQTT Standard for the Internet of Things
> Advisor, UK Government Technical Standards Board
> https://uk.linkedin.com/in/raphcohn
> +44 7590 675 756
>
> UK Office:
> Hamblethorpe Farm, Crag Lane, Bradley BD20 9DB, North Yorkshire, United
> Kingdom
> +44 845 3712 567
>
> Registered office:
> 16 Anchor Street, Chelmsford, Essex, CM2 0JY, United Kingdom
> StormMQ IT Limited is Registered in England and Wales under Company Number
> 07175657
>
> On 10 November 2015 at 07:58, Ringo De Smet <notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>>
> wrote:
>
> > @raphaelcohn <https://github.com/raphaelcohn> could you publish a new
> > packaged version?
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/raphaelcohn/swaddle/pull/34#issuecomment-155350142>.
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/raphaelcohn/swaddle/pull/34#issuecomment-156401654>.
>


-- 
*Ringo De Smet*
ReleaseQueue <http://www.releasequeue.com/>
ringo@releasequeue.com

**Comment by ringods** [comment]
Raphael,

Did you find the time to create that release? I can’t find it back on the swaddle github page.

Cheers,

Ringo De Smet


On 13 November 2015 at 12:20:21, Raphael Cohn (notifications@github.com) wrote:

Ringo

Can do Monday - does that work for you?

Raphael Cohn
Chief Architect, StormMQ
Co-Chair, OASIS MQTT Standard for the Internet of Things
Advisor, UK Government Technical Standards Board
https://uk.linkedin.com/in/raphcohn
+44 7590 675 756

UK Office:
Hamblethorpe Farm, Crag Lane, Bradley BD20 9DB, North Yorkshire, United
Kingdom
+44 845 3712 567

Registered office:
16 Anchor Street, Chelmsford, Essex, CM2 0JY, United Kingdom
StormMQ IT Limited is Registered in England and Wales under Company Number
07175657

**Comment by raphaelcohn** [comment]
I've tried but I've got bandwidth issues in this office (also had to fix
github changing their rest api). I'm back in my usual office Thu; I'll give
it a go in the evening.

**Comment by ringods** [comment]
@raphaelcohn sorry to ping you again. We are currently including the DEB version of swaddle into the creation of our Docker build images. Having the latest release would save us time creating our new build image, *and* shaves of 10 minutes of every of our builds as a result.

Can I just have a few minutes of your time to make that release?

**Comment by raphaelcohn** [comment]
Sorry.

GitHub have changed their API. I am at home tonight and will try my best.

**Comment by ringods** [comment]
Tnx!!

**Comment by raphaelcohn** [comment]
OK, some progress. Now I have problems because the version of rpm has changed in incompatible way on Mac OS X + homebrew. I hate package managers that auto-update to the latest version, and ignore forked projects...

**Comment by ringods** [comment]
Using latest is a bad release management practice. I still know why I'm building @ReleaseQueue. :-)
If you need a hand, I can make @chelarua available.

**Comment by raphaelcohn** [comment]
Yeah, I had a project a few years ago to version control debian package repositories. It just got too hard; whilst deb is probably the best binary package format around, the apt repo format just doesn't make it easy.

I'm going to try for another 30 mins or so to get brew to revert to an old rpm version, otherwise I'll set up a Linux box in a VM and go from there.

(FYI: It seems rpm --query --package <pathToPackage> is just hanging, with an error of 'NOKEY, key ID 1b9c4af0' - I suspect its use of gpg has changed. Might be something I can fix with gpg home.

**Comment by raphaelcohn** [comment]
OK, this is weird. If I run it as a background process, redirect stdout to a file then send it the TERM signal twice (kill <PSID>; kill <PSID>) I get the correct result. Some internal rpm process is hanging.

**Comment by raphaelcohn** [comment]
Some progress. Switched to an Ubuntu Trusty VM, had to workaround two defects in the default shell:-
* The tilde `~` is not properly escaped in all circumstances (fixed by setting `HOME` explicitly in shellfire and then using that)
* The internal redirect operator `contents="$(<"$myFile")" doesn't work; fixed by a UUOC, although not so useless in this situation

I now have a problem with the version of rpm here not co-operating with gpg... RPM really is a pain.

**Comment by raphaelcohn** [comment]
OK, got gpg to co-operate with RPM4.11 using a wrapper script. Yet more evidence of the very broken nature of RPM... Now got some more GitHub API issues - will see.

**Comment by raphaelcohn** [comment]
Progress good. I've sorted a few more bugs related to the shell in Ubuntu Trusty being slightly different. I've also fixed a bug in fatten that affected swaddle (fatten needs to use `/bin/bash`, not just any POSIX shell, because it needs `declare`). I've also added experimental checks to ensure ntpdate-debian is run if present so packaging uses a current timestamp in case of clock drift (which happends to some of my VMs when restored). Additionally, it turns out on Ubuntu / Debian that publishing GPG keys using hkps needs the `gnupg-curl` package to be installed (despite gnupg installing a curl wrapper). I've added that to swaddle's dependencies.

**Comment by raphaelcohn** [comment]
Released as https://github.com/raphaelcohn/swaddle/releases/tag/release_2015.1125.1709-1

**Comment by ringods** [comment]
@raphaelcohn thanks a lot!!

**Comment by chelarua** [comment]
A question pls. Not sure, but should this only work with bash? On an system where /bin/sh points to dash, i'm getting this error 'set: Illegal option -o braceexpand' while its setting some options in core_compatibility_setSaneShellOptions. Changing /bin/sh to point to bash or changing the swaddle shebang to '#!/usr/bin/env bash' work.

**Comment by raphaelcohn** [comment]
Yes, but other shells used to ignore it. Which version of dash are you
using? Ive seen some odd behaviour changes with the version on Ubuntu
Trusty. I built swaddle on trusty and had it package itself.

What complicates things here is some pdksh derived shells crash and burn
even if set +e is used before an invalid set -o...

**Comment by chelarua** [comment]
Saw the issue on trusty(14.04) and dash version is 0.5.7(0.5.7-4ubuntu1)

**Comment by ringods** [comment]
@raphaelcohn could you describe a bit more in detail what could be done here to fix this? If needed, I could let @chelarua look early January.

**Comment by stormmq** [comment]
Ringo,

I'm not 100% certain; as far as I can tell, there is a divergence in dash
shell behaviour on Ubuntu vs that built here from the upstream sources vs
that in BusyBox.. I think a fix needs to be made in swaddle. Sadly, there
are many forks of the dash / ash source code. I've got a bit of time today
and will take a look. One of the other irritations is that
"$(</path/to/file)" doesn't work either, even though I believe this is
standard POSIX. This means that the `cat` utility always needs to be on the
PATH.

Raph


Raphael Cohn
Chief Architect, StormMQ
Co-Chair, OASIS MQTT Standard for the Internet of Things
Advisor, UK Government Technical Standards Board
https://uk.linkedin.com/in/raphcohn
+44 7590 675 756

UK Office:
Hamblethorpe Farm, Crag Lane, Bradley BD20 9DB, North Yorkshire, United
Kingdom
+44 845 3712 567

Registered office:
16 Anchor Street, Chelmsford, Essex, CM2 0JY, United Kingdom
StormMQ IT Limited is Registered in England and Wales under Company Number
07175657

**Comment by raphaelcohn** [comment]
OK, I might have found out what's going on. There's a legacy file in
shellfire/code called compatibility.bash.functions, that only gets loaded
if the shell is bash. The shell is bash when fatten runs, as it needs'
bash's function export builtin, `declare`. This is about the only part of
shellfire that uses bash-specific features. I think what might have
happened is that this got loaded whilst fattening swaddle and overwrote the
shell compatibility settings. What I've done is removed the legacy file,
and changed the load code so it is now impossible for shellfire to load
alternative implementations of functions (this means the code can only make
use of POSIX features; something I did a long time ago to the rest of the
code base). I'll look at making another release.


Raphael Cohn
Chief Architect, StormMQ
Co-Chair, OASIS MQTT Standard for the Internet of Things
Advisor, UK Government Technical Standards Board
https://uk.linkedin.com/in/raphcohn
+44 7590 675 756

UK Office:
Hamblethorpe Farm, Crag Lane, Bradley BD20 9DB, North Yorkshire, United
Kingdom
+44 845 3712 567

Registered office:
16 Anchor Street, Chelmsford, Essex, CM2 0JY, United Kingdom
StormMQ IT Limited is Registered in England and Wales under Company Number
07175657

**Comment by raphaelcohn** [comment]
OK, I've made a new release of swaddle:
https://github.com/raphaelcohn/swaddle/releases/tag/release_2015.1127.1359-1

Raphael Cohn
Chief Architect, StormMQ
Co-Chair, OASIS MQTT Standard for the Internet of Things
Advisor, UK Government Technical Standards Board
https://uk.linkedin.com/in/raphcohn
+44 7590 675 756

UK Office:
Hamblethorpe Farm, Crag Lane, Bradley BD20 9DB, North Yorkshire, United
Kingdom
+44 845 3712 567

Registered office:
16 Anchor Street, Chelmsford, Essex, CM2 0JY, United Kingdom
StormMQ IT Limited is Registered in England and Wales under Company Number
07175657

**Pull request merged**
